[package]
name = "pebblecrypt"
version = "0.1.2"
edition = "2024"
rust-version = "1.95"
description = "A small native Windows file encryption app"
license = "MIT"
build = "build.rs"

[dependencies]
age = { version = "0.12.1", default-features = false }
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "accesskit"] }
rfd = "0.17"
getrandom = "0.4"
tempfile = "3.27"
zeroize = "1.8"

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[profile.dev.package.scrypt]
opt-level = 3

[profile.dev.package.salsa20]
opt-level = 3

[profile.dev.package.pbkdf2]
opt-level = 3
